node_js:
  - "6"
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - lcov
 
os:
  - linux
  - osx

install:
  - npm install -g surf-build@1.0.0-beta.3 
script:
  - surf-build -n "surf-travis-$TRAVIS_OS_NAME"
