language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - lcov
 
os:
  - linux
  - osx

script:
  - npm install -g surf-build@1.0.0-beta.3
  - surf-build -n "surf-travis-$TRAVIS_OS_NAME"
