language: node_js
dist: trusty
node_js:
  - "6.3.0"
compiler:
  - clang

os:
  - linux
  - osx

install:
  - npm install -g surf-build@1.0.0-beta.3 
script:
  - surf-build -n "surf-travis-$TRAVIS_OS_NAME"
